apiVersion: v1
kind: Secret
metadata:
  name: django-env-secret
  namespace: django-app
type: Opaque
stringData:
  POSTGRES_DB: fleetdb
  POSTGRES_USER: roy77
  POSTGRES_PASSWORD: asdf1234@77
  PYTHONUNBUFFERED: "1"
  POSTGRES_HOST: postgres
  STRIPE_SECRET_KEY: "sk_test_your_test_key_here"
  STRIPE_PUBLIC_KEY: "pk_test_your_test_key_here"
  STRIPE_WEBHOOK_SECRET: "whsec_your_test_key_here"
  SITE_URL: "http://93.127.195.189:5000"
  FRONTEND_SITE_URL: "https://finch-development.vercel.app"
